# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/accounts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/accounts.proto\"H\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\x05\"\'\n\x14RegisterUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x10LoginUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\x05\"$\n\x11LoginUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2x\n\x05Users\x12;\n\x0cRegisterUser\x12\x14.RegisterUserRequest\x1a\x15.RegisterUserResponse\x12\x32\n\tLoginUser\x12\x11.LoginUserRequest\x1a\x12.LoginUserResponseb\x06proto3')



_REGISTERUSERREQUEST = DESCRIPTOR.message_types_by_name['RegisterUserRequest']
_REGISTERUSERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterUserResponse']
_LOGINUSERREQUEST = DESCRIPTOR.message_types_by_name['LoginUserRequest']
_LOGINUSERRESPONSE = DESCRIPTOR.message_types_by_name['LoginUserResponse']
RegisterUserRequest = _reflection.GeneratedProtocolMessageType('RegisterUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERUSERREQUEST,
  '__module__' : 'proto.accounts_pb2'
  # @@protoc_insertion_point(class_scope:RegisterUserRequest)
  })
_sym_db.RegisterMessage(RegisterUserRequest)

RegisterUserResponse = _reflection.GeneratedProtocolMessageType('RegisterUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERUSERRESPONSE,
  '__module__' : 'proto.accounts_pb2'
  # @@protoc_insertion_point(class_scope:RegisterUserResponse)
  })
_sym_db.RegisterMessage(RegisterUserResponse)

LoginUserRequest = _reflection.GeneratedProtocolMessageType('LoginUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINUSERREQUEST,
  '__module__' : 'proto.accounts_pb2'
  # @@protoc_insertion_point(class_scope:LoginUserRequest)
  })
_sym_db.RegisterMessage(LoginUserRequest)

LoginUserResponse = _reflection.GeneratedProtocolMessageType('LoginUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINUSERRESPONSE,
  '__module__' : 'proto.accounts_pb2'
  # @@protoc_insertion_point(class_scope:LoginUserResponse)
  })
_sym_db.RegisterMessage(LoginUserResponse)

_USERS = DESCRIPTOR.services_by_name['Users']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERUSERREQUEST._serialized_start=24
  _REGISTERUSERREQUEST._serialized_end=96
  _REGISTERUSERRESPONSE._serialized_start=98
  _REGISTERUSERRESPONSE._serialized_end=137
  _LOGINUSERREQUEST._serialized_start=139
  _LOGINUSERREQUEST._serialized_end=193
  _LOGINUSERRESPONSE._serialized_start=195
  _LOGINUSERRESPONSE._serialized_end=231
  _USERS._serialized_start=233
  _USERS._serialized_end=353
# @@protoc_insertion_point(module_scope)
